### ISSUE TITLE
Crash when calling Triangulator#triangulateDelaunay due to assertionFailure.

### ISSUE THREAD

**Issue by kenzan8000** [iShape-Swift/iShapeTriangulation#2]
I debuged [the triangulation of geojson's multipolygon features](https://github.com/bathymetric-cam/bathymetric-cam-ios/blob/main/bathymetry/AR/ARBathymetryNode.swift#L110), and experienced a crash due to [the assertionFailure](https://github.com/iShape-Swift/iShapeTriangulation/blob/master/Sources/iShapeTriangulation/Triangulation/PlainShape/PlainShape%2BLayout.swift#L479).

How can I avoid the assertionFailure?
Since the triangulation logic is a bit complicated for me to get the picture, I'm not very sure how that works.

Here is [a sample project](https://github.com/kenzan8000/iShapeTriangulationSample/blob/main/iShapeTriangulationSample/AppDelegate.swift#L17) reproducing the crash.
<img width="1196" alt="Screen Shot 2021-08-04 at 10 19 49 PM" src="https://user-images.githubusercontent.com/225808/128189785-113a31b8-fb9b-499a-815d-c12e2ace432c.png">

Thanks!

**Comment by NailxSharipov** [comment]
I'll see this example. Most of the time you will get this failure if a path
has self intersections.

**Comment by kenzan8000** [comment]
@NailxSharipov Drew the path on qgis app. It looks like there are intersections as you said above.

<img width="1791" alt="Screen Shot 2021-08-05 at 12 37 55 AM" src="https://user-images.githubusercontent.com/225808/128210674-b83fb55f-4355-47fc-a329-9040bcc55efc.png">

It would be great if the library would throw the error instead of calling assertionFailure.

Anyway, I'll be removing the intersections from the geojson files. (and maybe making the pull request)

**Comment by NailxSharipov** [comment]
I thoght about your words and throwing an exception is looking good.

Right now this algorithm is not support self intersections, cause I hadn't
this purporse. In other hand it's not so hard to implement.

We are spliting path into separate "correct" pathes. As the result we will
get a clock-wise and counter clock-wise pathes. Then we should decide which
of them we must triangulate all of them or just clock-wise pathes. I think
it must be kind of enum parameter with this rule logic.

**Comment by kenzan8000** [comment]
Oh, that sounds really complicated to work on the triangulation that the source path has the intersections in it.
> We are spliting path into separate "correct" pathes. As the result we will
get a clock-wise and counter clock-wise pathes. Then we should decide which
of them we must triangulate all of them or just clock-wise pathes.

Just throwing the error when the path isn’t “correct” would be simpler.

**Comment by NailxSharipov** [comment]
Finally, I've added try/catch functionality with the detection problem mechanism. Now all functions like triangulation Delaunay throw an exception with the detail information what's going wrong
