### ISSUE TITLE
Missing return statement when DEBUG mode is turned off.

### ISSUE THREAD

**Issue by Agnakaraara** [iShape-Swift/iShapeTriangulation#3]
Library won't compile in RELEASE mode. There is a missing return statement on line 62 in the Simplificator file inside iGeometry module. Please fix.

**Comment by NailxSharipov** [comment]
Thank you for your feedback. Very strange mistake, look like I never compiled in release mode :). I've just release 1.0.2 with the fix.

**Comment by Agnakaraara** [comment]
Thanks a lot!
