### ISSUE TITLE
Does it support for Counterclockwise Polygon

### ISSUE THREAD

**Issue by santosh-2023** [iShape-Swift/iShapeTriangulation#5]
Does it support for Counterclockwise Polygon

**Comment by NailxSharipov** [comment]
No. 

Cause it's not a problem to invert path by your own. 

If you don't know is it clockwise or counter clockwise you can calculate area of the polygon and see it's sign

You can use for this spacial method for [IntPoint] from iGeometry

`
public extension Array where Element == IntPoint {

    @inlinable
    var area: Int64 {
        guard var p1 = self.last else {
            return 0
        }
        
        var sum: Int64 = 0
        
        for p2 in self {
            let x = p2.x &- p1.x
            let y = p2.y &+ p1.y
            sum &+= x * y
            p1 = p2
        }

        return sum >> 1
    }
    
    @inlinable
    mutating func invert() {
        let n = self.count
        let m = n >> 1
        for i in 0..<m {
            let j = n - i - 1
            let a = self[i]
            let b = self[j]
            self[i] = b
            self[j] = a
        }
    }
}
`

**Comment by santosh-2023** [comment]
@NailxSharipov It helped, One more point about other shape which is mix of both. I am attaching screenshot,please share your thought.

<img width="308" alt="Screenshot 2023-08-10 at 7 33 32 PM" src="https://github.com/iShape-Swift/iShapeTriangulation/assets/128692873/e528f503-85e2-494a-b541-e196400c99a2">

**Comment by NailxSharipov** [comment]
It's unclosed path. If we close it it will be a self-intersecting polygon.
To triangulate it you need resolve this by your own first.
Right now I am finsihing my other library which is poly bool library. Supports operations line self-intersecting, union, subtract an so on.
After I finish it I will add this functionality. But not to this library but in other similar one. I decided to update api and some other things.

I think it will be ready on next week

**Comment by santosh-2023** [comment]
nice, I will be waiting for that library, could you please do favour for me and share link here if possible :) Thank You

**Comment by NailxSharipov** [comment]
Hello! Looks like I released this new library. Hope you enjoy it.
https://github.com/iShape-Swift/iTriangle
